version: "3.8"

services:
  bankDB:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=bank
    ports:
      - 5432:5432
    # volumes:
    #   - ./initdbs/bank_init.sql:/docker-entrypoint-initdb.d/bank_init.sql
